sudo: required
services:
  - docker

before_install:
  - docker build -t umutyilmaz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true umutyilmaz/docker-react npm run test -- --coverage